name: Integration Tests

on:
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Start Functions host (optional)
        run: |
          echo "If you need to start the Functions host, configure this step."
      - name: Run integration tests
        run: |
          python -m pytest -q -k integration
